name: Deploy to Server
on:
  push:
    paths-ignore:
      - '.gitignore'
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ['self-hosted']
    environment: api-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules/
          key: ${{ runner.os }}-cargo
      - run: bun install
      - run: bun run build
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy
        run: scp -i ~/.ssh/id_rsa -r dist/* root@omaralkersh.com:/var/www/s3-browser
